### ISSUE TITLE
Post - note text editor

### ISSUE THREAD

**Issue by jmanyoma** [lnkit/lnkit#40]
On selectuon of bold or italic there is no toggle css to verify it is on.

![quickmemo _2015-02-20-07-19-00](https://cloud.githubusercontent.com/assets/7595999/6286052/1abc6c10-b8d1-11e4-9a0a-b559eb30c86b.png)

**Comment by lnkit** [comment]
Temp Patch till conversion is done. Will have to revisit many issues with blog posts.
